Repository flow-build/diagrams-core, pull requests merged in 2022-10, with the labels that each got.

#4 chore(release): 1.1.0
  package-lock.json
  package.json
Labels: configuration, dependencies

#5 Feature/fbs 82
  db/migrations/20221014150432_create_blueprints_table.js
  db/migrations/20221014153521_create_workflows_table.js
  db/migrations/20221014154948_create_diagram_to_workflow_table.js
  db/migrations/20221014160432_rename_workflow_id_on_diagrams.js
  db/seeds/seed-test-blueprint.js
  db/seeds/seed-test-diagram.js
  db/seeds/seed-test-workflow.js
  db/seeds/seed-tests-diagram-to-workflow.js
  examples/blueprint.js
  index.js
  package-lock.json
  src/blueprintCore.js
  src/diagramCore.js
  src/diagramToWorkflowCore.js
  src/entities/base.js
  src/entities/blueprint.js
  src/entities/diagram.js
  src/entities/diagramToWorkflow.js
  src/entities/workflow.js
  src/persist/knex.js
  src/persist/provider.js
  src/tests/blueprintCore.test.js
  src/tests/diagramCore.test.js
  src/tests/diagramToWorkflowCore.test.js
  src/tests/unit/blueprint.test.js
  src/tests/unit/diagram.test.js
  src/tests/unit/diagramToWorkflow.test.js
  src/tests/unit/workflow.test.js
  src/tests/workflowCore.test.js
  src/workflowCore.js
Labels: configuration, js, test

#6 chore(release): 1.2.0
  package-lock.json
  package.json
Labels: configuration, dependencies

#7 fix: adjust diagram2workflow to accept relation N:N
  db/migrations/20221014154948_create_diagram_to_workflow_table.js
  src/diagramToWorkflowCore.js
  src/entities/base.js
  src/persist/knex.js
  src/tests/diagramToWorkflowCore.test.js
  src/tests/unit/diagramToWorkflow.test.js
Labels: js, test

#8 chore(release): 1.2.1
  package-lock.json
  package.json
Labels: configuration, dependencies

#9 feat: add methods to update and delete new entities
  src/blueprintCore.js
  src/diagramToWorkflowCore.js
  src/entities/base.js
  src/persist/knex.js
  src/tests/blueprintCore.test.js
  src/tests/diagramToWorkflowCore.test.js
  src/tests/workflowCore.test.js
  src/workflowCore.js
Labels: js, test

#10 chore(release): 1.3.0
  package-lock.json
  package.json
Labels: configuration, dependencies

#12 ci: add development branch on release action
  .github/workflows/publish-packages.yml
Labels: github-actions

#14 Fix/release and migrations
  .github/workflows/publish-packages.yml
  .releaserc.json
  db/migrations/20220815135910_create_diagrams_table.js
  db/migrations/20221014154948_create_diagram_to_workflow_table.js
Labels: github-actions

#16 chore(release): 1.3.1-rc.1
  package-lock.json
  package.json
Labels: configuration, dependencies

#18 chore(release): 1.3.1
  package-lock.json
  package.json
Labels: configuration, dependencies
