Repository flow-build/diagrams-core, pull requests merged in 2023-05, with the labels that each got.

#28 chore(release): 1.6.0-rc.1
  package-lock.json
  package.json
Labels: configuration, dependencies

#30 chore(release): 1.6.0-rc.2
  package-lock.json
  package.json
Labels: configuration, dependencies

#31 fix: adjust method getAllServers of serverCore
  db/migrations/20230503190851_create_server_table.js
  db/seeds/seed-test-server.js
  src/entities/server.js
  src/persist/knex.js
  src/serverCore.js
  src/tests/serverCore.test.js
  src/tests/unit/server.test.js
Labels: js, test

#32 chore(release): 1.6.0-rc.3
  package-lock.json
  package.json
Labels: configuration, dependencies

#34 Feature/adm 198
  db/migrations/20230503190858_create_workflow_table.js
  src/persist/knex.js
  src/serverCore.js
  src/tests/diagramCore.test.js
  src/tests/serverCore.test.js
  src/tests/unit/server.test.js
Labels: js, test

#35 chore(release): 1.6.0-rc.4
  package-lock.json
  package.json
Labels: configuration, dependencies

#36 Feature/adm 201
  src/diagramCore.js
  src/entities/diagram.js
  src/persist/knex.js
  src/tests/diagramCore.test.js
Labels: js, test

#37 chore(release): 1.6.0-rc.5
  package-lock.json
  package.json
Labels: configuration, dependencies

#38 feat: updates 'getByUserAndWF' query
  src/persist/knex.js
Labels: js

#39 chore(release): 1.6.0-rc.6
  package-lock.json
  package.json
Labels: configuration, dependencies

#40 Refactor/style
  .eslintrc.js
  .husky/pre-commit
  .prettierrc
  db/migrations/20230503190508_create_blueprint_table.js
  db/migrations/20230503190509_create_diagram_table.js
  db/migrations/20230503190851_create_server_table.js
  db/migrations/20230503190858_create_workflow_table.js
  db/migrations/20230510151044_create_type_column.js
  db/seeds/seed-test-blueprint.js
  db/seeds/seed-test-diagram.js
  db/seeds/seed-test-server.js
  db/seeds/seed-test-workflow.js
  examples/blueprint.js
  index.js
  jest.config.js
  knexfile.js
  package-lock.json
  package.json
  src/blueprintCore.js
  src/diagramCore.js
  src/entities/base.js
  src/entities/blueprint.js
  src/entities/diagram.js
  src/entities/server.js
  src/entities/workflow.js
  src/persist/knex.js
  src/persist/persist.js
  src/persist/provider.js
  src/serverCore.js
  src/tests/blueprintCore.test.js
  src/tests/diagramCore.test.js
  src/tests/serverCore.test.js
  src/tests/unit/blueprint.test.js
  src/tests/unit/diagram.test.js
  src/tests/unit/server.test.js
  src/tests/unit/workflow.test.js
  src/tests/workflowCore.test.js
  src/utils/db.js
  src/utils/factory.js
  src/utils/logger.js
  src/workflowCore.js
Labels: configuration, dependencies, js, test

#42 chore(release): 1.6.0-rc.7
  package-lock.json
  package.json
Labels: configuration, dependencies

#43 Feature/add fetch by url method
  src/entities/server.js
  src/persist/knex.js
  src/serverCore.js
  src/tests/serverCore.test.js
  src/tests/unit/server.test.js
Labels: js, test

#44 chore(release): 1.6.0-rc.8
  package-lock.json
  package.json
Labels: configuration, dependencies

#46 chore(release): 1.6.0-rc.9
  package-lock.json
  package.json
Labels: configuration, dependencies

#47 Fix/flow 101
  .env.docker
  src/diagramCore.js
  src/persist/knex.js
  src/tests/diagramCore.test.js
  src/utils/logger.js
Labels: configuration, js, test

#48 chore(release): 1.6.0-rc.10
  package-lock.json
  package.json
Labels: configuration, dependencies

#50 chore(release): 1.6.0
  package-lock.json
  package.json
Labels: configuration, dependencies
